project_id = "ipjrhuijvgchbezcjhsk"

[auth]
site_url = "https://preview--leadapp-mokube.lovable.app"
additional_redirect_urls = ["https://preview--leadapp-mokube.lovable.app"]

[auth.hook.send_sms]
enabled = false

[auth.hook.send_email]
enabled = false

# Database webhook for auth events
[database]
  [[database.webhooks]]
  enabled = true
  name = "save-oauth-tokens"
  table = "users"
  schema = "auth"
  events = ["INSERT"]
  function_name = "save-oauth-tokens"
  function_args = {}

[functions.configure-sandbox]
verify_jwt = false

[functions.create-event]
verify_jwt = true

[functions.delete-conversation]
verify_jwt = true

[functions.get-calendars]
verify_jwt = true

[functions.get-events]
verify_jwt = true

[functions.list-emails]
verify_jwt = true

[functions.nylas-oauth-redirect]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.twilio-status-callback]
verify_jwt = false

[functions.disconnect-calendar]
verify_jwt = false

[functions.handle-auth-callback]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.accept-invite]
verify_jwt = true

[functions.save-oauth-tokens]
verify_jwt = false

[functions.calendar-fetch]
verify_jwt = true