project_id = "ipjrhuijvgchbezcjhsk"

[auth]
site_url = "https://preview--leadapp-mokube.lovable.app"
additional_redirect_urls = ["https://preview--leadapp-mokube.lovable.app"]

# Auth webhook voor OAuth token opslag
[auth.hook.custom_access_token]
enabled = true
uri = "https://ipjrhuijvgchbezcjhsk.supabase.co/functions/v1/save-oauth-tokens"

[auth.hook.send_sms]
enabled = false

[auth.hook.send_email]
enabled = false

[functions.configure-sandbox]
verify_jwt = false

[functions.create-event]
verify_jwt = true

[functions.delete-conversation]
verify_jwt = true

[functions.get-calendars]
verify_jwt = true

[functions.get-events]
verify_jwt = true

[functions.list-emails]
verify_jwt = true

# Edge functions configuration can be added here as needed

[functions.twilio-webhook]
verify_jwt = false

[functions.twilio-status-callback]
verify_jwt = false

[functions.disconnect-calendar]
verify_jwt = false

[functions.handle-auth-callback]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.accept-invite]
verify_jwt = true

[functions.save-oauth-tokens]
verify_jwt = false

[functions.calendar-fetch]
verify_jwt = true